"""Phase 6: scenario tree with multi-stage non-anticipativity.

A simple two-stage-decision tree (root + IDA-node layer + leaves):
- ROOT      one node. Decision: q_DA (here-and-now, shared by all leaves).
- IDA NODES K branches sampled by clustering base scenarios on a stage-1
            feature (e.g. mean DA price in the first part of the day). Decision
            per IDA node: q_ID (shared by all leaves descending from it).
- LEAVES    full price/solar paths. Decision per leaf: dispatch (charge,
            discharge, soc, curtail, imbalance).

Non-anticipativity is enforced by construction: q_DA is a single variable, q_ID
is indexed by IDA node only, and dispatch is leaf-specific.

The tree is built from N_base scenarios already generated by `ForecastGenerator`:
1. Compute a stage-1 feature for each base scenario (default: mean DA price
   in the first half of the trading window).
2. K-means cluster the feature into `n_ida_nodes` groups -> IDA nodes.
3. Each base scenario becomes a leaf, mapped to its cluster.
4. Probabilities: equal across leaves (or proportional to base probabilities).
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd

from solarbess.forecast.scenarios import ScenarioForecast


@dataclass(frozen=True)
class ScenarioTree:
    timestamps: pd.DatetimeIndex
    leaf_ids: np.ndarray            # (L,)
    leaf_probabilities: np.ndarray  # (L,) sums to 1
    leaf_to_ida: np.ndarray         # (L,) maps leaf -> IDA node id in [0, K)
    ida_node_ids: np.ndarray        # (K,)
    ida_probabilities: np.ndarray   # (K,) sums to 1
    # Per-leaf paths
    solar_mw: np.ndarray            # (L, T)
    da_price: np.ndarray            # (L, T)
    id_price: np.ndarray            # (L, T)
    imb_surplus: np.ndarray         # (L, T)
    imb_shortfall: np.ndarray       # (L, T)

    def __post_init__(self) -> None:
        L, T = self.solar_mw.shape
        assert self.leaf_ids.shape == (L,)
        assert self.leaf_probabilities.shape == (L,)
        assert self.leaf_to_ida.shape == (L,)
        assert self.timestamps.shape == (T,)
        assert abs(self.leaf_probabilities.sum() - 1.0) < 1e-9
        assert abs(self.ida_probabilities.sum() - 1.0) < 1e-9


def build_tree_from_scenarios(
    base: ScenarioForecast,
    n_ida_nodes: int,
    stage1_feature: str = "da_price_first_half",
    seed: int = 0,
) -> ScenarioTree:
    """Cluster `base` scenarios into `n_ida_nodes` IDA branches.

    Uses a simple sort-and-split clustering on the chosen 1-D stage-1 feature -
    deterministic, dependency-free, gives roughly equal cluster sizes.
    """
    L, T = base.solar_mw.shape
    if n_ida_nodes < 1:
        raise ValueError("n_ida_nodes must be >= 1")
    if n_ida_nodes > L:
        n_ida_nodes = L

    half = T // 2 if T >= 2 else 1
    if stage1_feature == "da_price_first_half":
        feat = base.da_price[:, :half].mean(axis=1)
    elif stage1_feature == "solar_first_half":
        feat = base.solar_mw[:, :half].mean(axis=1)
    elif stage1_feature == "da_price_total":
        feat = base.da_price.mean(axis=1)
    else:
        raise ValueError(f"unknown stage1_feature {stage1_feature!r}")

    # Sort base scenarios by feature, split into n equal-sized buckets.
    order = np.argsort(feat)
    bucket_assignments = np.empty(L, dtype=np.int64)
    bucket_size = L // n_ida_nodes
    remainder = L % n_ida_nodes
    start = 0
    for k in range(n_ida_nodes):
        size = bucket_size + (1 if k < remainder else 0)
        bucket_assignments[order[start:start + size]] = k
        start += size

    leaf_probs = base.probabilities / base.probabilities.sum()
    # Aggregate IDA probabilities
    ida_probs = np.zeros(n_ida_nodes)
    for k in range(n_ida_nodes):
        ida_probs[k] = leaf_probs[bucket_assignments == k].sum()
    ida_probs = ida_probs / ida_probs.sum()  # normalise for safety

    return ScenarioTree(
        timestamps=base.timestamps,
        leaf_ids=base.scenario_ids.astype(np.int64),
        leaf_probabilities=leaf_probs,
        leaf_to_ida=bucket_assignments,
        ida_node_ids=np.arange(n_ida_nodes),
        ida_probabilities=ida_probs,
        solar_mw=base.solar_mw,
        da_price=base.da_price,
        id_price=base.id_price,
        imb_surplus=base.imb_surplus,
        imb_shortfall=base.imb_shortfall,
    )
